FROM postgres:16-alpine

RUN apk add --no-cache just git \
    icu-libs \
    icu-data-full bash util-linux

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN mkdir -p /usr/src/scripts/

COPY justfile /usr/src/scripts/justfile
COPY migrations /usr/src/scripts/migrations