set dotenv-load

migrate-down-0001:
    -psql "$DATABASE_URL" -f 0001-scraper-profile.sql

migrate-down-0002:
    -psql "$DATABASE_URL" -f 0002-profile-links.sql

all:
    #!/bin/sh
    ls *.sql | column -t | sort --reverse | xargs -I {} psql "${DATABASE_URL}" -f {} || true
